#!/bin/sh
while read -r file; do
    case "$1" in
    "w") setbg "$file" & ;;
    "r")
        magick "$file" -rotate 90 "$file"
        ;;
    "R")
        magick "$file" -rotate -90 "$file"
        ;;
    "f")
        magick "$file" -flop "$file"
        ;;
    "y")
        printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
            notify-send "$file copied to clipboard" &
        ;;
    "Y")
        readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
            notify-send "$(readlink -f "$file") copied to clipboard" &
        ;;
    "d")
        [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted."
        ;;
    esac
done
