#!/usr/bin/bash
export XINITRC="$XDG_CONFIG_HOME/bash/xinitrc"
# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.config/bash/bashrc" ]; then
        . "$HOME/.config/bash/bashrc"
    fi
fi
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:/sbin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"
# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
