#!/bin/bash

# Set environment variables
export PATH="$HOME/.config/bspwm/src:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

MonitorSetup
bspc config external_rules_command "$HOME/.config/bspwm/src/ExternalRules"

bspc config window_gap 5
bspc config split_ratio 0.53
bspc config single_monocle true

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config removal_adjustment true

bspc config border_width 2
bspc config normal_border_color "#1a1b26"
bspc config active_border_color "#364A73"
bspc config focused_border_color "#222940"

bspc config presel_feedback_color "#577bca"
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 50
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner
bspc config pointer_action2 resize_side
bspc config -m HDMI-0 top_padding 34

# fullscreen
bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [ "$state" != "fullscreen" ]; then
        continue
    fi
    if [ "$flag" == on ]; then
        eww -c $HOME/.config/eww close-all
    else
        eww -c $HOME/.config/eww open bar
    fi
done &
#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩
$HOME/.config/bspwm/src/autostart.sh
